### ISSUE TITLE
Change how weighting works

### ISSUE THREAD

**Issue by tysmith** [MozillaSecurity/avalanche#2]
Perhaps making weighting work by specifying weight relative to the max weight vs relative to total weight of choices. My hope is that this is easier to work with for a human.

Ex: In this example "c" should be chosen 1 in 100 times vs 1 in 201 times (current functionality).

```
A    100   "a"
     100   "b"
     1     "c"
```

**Comment by tysmith** [comment]
The conclusion of the discussion was that this is likely the way to do it for now anyways.

**Comment by jschwartzentruber** [comment]
Another idea was to restrict weights to floats between 0-1. 1 would continue to be the norm when adding to choices.

The current implementation (integers) makes it easy to increase the likelihood of a choice, but hard to decrease it. A floating point implementation capped at 1 would have the opposite effect, which I think matches the usual need better.

**Comment by jschwartzentruber** [comment]
Fixed in 1cbb10fd2c9112b099ffbee37fe1fff568912090
