### ISSUE TITLE
ValueError raised by rndint() and rndpow2()

### ISSUE THREAD

**Issue by tysmith** [MozillaSecurity/avalanche#5]
"ValueError: empty range for randrange() (2,2, 0)" is raised when the first arg is larger than the second.

Grammar to reproduce:
`root       rndint(2,1)`

"ValueError: empty range for randrange() (0,0, 0)" is raised when passing a negative number as the first arg to rndpow2()

Grammar to reproduce:
`root       rndpow2(-1,0)`

These should likely raise an exception but we should provide a better message with a line number.

**Comment by jschwartzentruber** [comment]
Why doesn't rndflt() do this too?

**Comment by tysmith** [comment]
random.uniform()[1] doesn't seem to care what order you pass the args.

[1]https://docs.python.org/3.5/library/random.html#random.uniform

**Comment by jschwartzentruber** [comment]
Hmm. Weird. `help(random.uniform)` is not so helpful.
